//
//  kvmeta.hpp
//
//  Created by MNN on 2025/04/08.
//  Copyright © 2018, Alibaba Group Holding Limited
//

#ifndef KVMETA_hpp
#define KVMETA_hpp

#include <cstdint>
#include <vector>

namespace MNN {
using namespace Express;
namespace Transformer {

struct KVMeta {
    enum {
        NoChange,
        PendingWrite,
        PendingRead
    } file_operation;
    size_t block = 4096;
    size_t previous = 0;
    size_t remove = 0;
    int* reserve = nullptr;
    int n_reserve = 0;
    size_t add = 0;
    std::string file_name = "";
    int file_flag = NoChange;
    int seqlen_in_disk = 0;
    int layer_index = 0;
    int layer_nums = 0;

    // H2O runtime configuration (set by llm config).
    int h2o_enable = 0;
    int h2o_block_tokens = 64;
    int h2o_sink_tokens = 32;
    int h2o_recent_tokens = 256;
    float h2o_target_keep_ratio = 0.50f;
    float h2o_ema_alpha = 0.90f;
    int h2o_update_interval = 16;
    int h2o_trigger_min_tokens = 512;
    int h2o_log_stats = 0;
    int h2o_lossless_enable = 0;
    int h2o_lossless_codec = 0; // 0:none 1:gear_delta
    int h2o_in_decode = 0;

    // Next-step pending compact plan generated by H2O.
    size_t h2o_pending_remove = 0;
    int* h2o_pending_reserve = nullptr;
    int h2o_pending_n_reserve = 0;
    int h2o_pending_plan_ready = 0;

    // Runtime stats.
    float h2o_keep_ratio = 1.0f;
    float h2o_lossy_ratio = 1.0f;
    float h2o_lossless_ratio = 1.0f;
    int64_t h2o_evict_us = 0;
    int64_t h2o_codec_us = 0;
    int h2o_last_evict_tokens = 0;
    int h2o_total_evict_tokens = 0;

    std::vector<int> reserveHost;
    void sync();
};

}
}
#endif // KVMATE_hpp
